_target_: navsim.agents.diffusiondrivev2.diffusiondrivev2_rl_agent.Diffusiondrivev2_Rl_Agent
_convert_: 'all'

config:
  _target_: navsim.agents.diffusiondrivev2.diffusiondrivev2_rl_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: null
lr: 2e-4
